config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]
  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  mount ActionCable.server => '/cable'

  match "/register_email" => "omnitokens#register_email", :via => :post
  match "/verify_email" => "omnitokens#verify_email", :via => :get

  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :subsribe

  scope :digest, ->{ where(created_at: Date.current.at_beginning_of_day..Date.current.at_end_of_day) }

  private

  def subsribe
    self.subscriptions.create(user: self.user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with(@questions, each_serializer: QuestionsSerializer)
  end

  def show
    @question = Question.find(params[:id])
    respond_with(@question)
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with(@question)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]

  after_action :publish_question, only: [:create]

  respond_to :html

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
    @answer.attachments.build
  end

  def new
    respond_with(@question = current_user.questions.new)
    @question.attachments.build
  end

  def edit
    # apply load_question
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    respond_with(@question)
  end

  private

  def build_answer
    gon.question_id = @question.id
    @answer = @question.answers.new
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions', @question)
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_comment.html.slim
- cache comment do
  p = comment.body

app/views/questions/_comments.html.slim
.comments
  - entity.comments.each do |comment|
    = render 'questions/comment', comment: comment
- if can?(:create, Comment)
  = form_for entity.comments.build, remote: true, format: :json do |f|
    p= f.label :body, 'Comment'
    p= f.text_area :body
    = f.hidden_field :commentable_id, value: entity.id
    = f.hidden_field :commentable_type, value: entity.class.name
    p= f.submit 'Create comment'

app/views/questions/_question.html.slim
- cache question do
  h1
    = question.title
  p
    = question.body
p.subscription
  = render 'subscriptions/subscription', question: question

div class="question-votes-#{question.id}"
  = render 'questions/vote', entity: question
p
  | Attachments:
ul
  - question.attachments.each do |attach|
    li = link_to attach.file.identifier, attach.file.url

- if can?(:destroy, question)
  = button_to 'Delete question', question, method: :delete
- if can?(:update, question)
  = link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: question.id }, remote: true

= render 'questions/comments', entity: question

- if can?(:update, Question)
  = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title, "Title"
      = f.text_area :title
      = f.label :body, "Question"
      = f.text_area :body
      = f.submit 'Save'

app/views/questions/_vote.html.slim
- cache ['rating', entity] do
  b.rating= entity.rating
| &nbsp
- if can?(:create, Vote)
  div class= delete_vote_class(entity)
    = link_to 'Delete vote', delete_vote_path(entity),
            method: :delete, remote: true, data: { type: :json }
  div class= up_down_vote_class(entity)
    = link_to 'Up', votes_path(votable_id: entity.id, votable_type: entity.class.name, up: true),
            method: :post, remote: true, data: { type: :json }
    | &nbsp
    = link_to 'Down', votes_path(votable_id: entity.id, votable_type: entity.class.name, up: false),
            method: :post, remote: true, data: { type: :json }

app/views/questions/index.html.slim
p= link_to 'Search', search_path

- cache @questions do
  .questions
    - if can?(:create, Question)
      = link_to 'Ask question', new_question_path

    h1 questions:
    - @questions.each do |question|
      h3 = link_to question.title, question

app/views/questions/new.html.slim
= form_for @question do |f|
  = render 'common/errors', resource: @question
  = f.label :title
  = f.text_field :title
  br
  = f.label :body
  = f.text_area :body
  = render 'attachments/form', f: f
  = f.submit 'Create'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
.question
  = render @question

.answers *{'data-question-id'=>@question.id}
  = render @question.answers
   div class="answer-votes-#{answer.id}"
    = render 'questions/vote', entity: answer

- if can?(:create, Answer)
  = form_for [@question, @answer], remote: true do |f|
    = render 'common/errors', resource: @answer
    .answer-errors
    = f.text_area :body
    = render 'attachments/form', f: f
    p = f.submit 'Add new answer'

= link_to 'Back', questions_path

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#<%= @question.id %>.question').html('<%= j render @question %>');
<% end %>