config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]
  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  mount ActionCable.server => '/cable'

  match "/register_email" => "omnitokens#register_email", :via => :post
  match "/verify_email" => "omnitokens#verify_email", :via => :get

  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  has_many :attachments, as: :attachable, dependent: :destroy

  validates :body, presence: true, length: { minimum: 3 }

  after_create :notify_subsribers

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :first_best, -> { order('best DESC') }

  def mark_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
    end
  end

  private

  def notify_subsribers
    SubscriptionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:destroy, :update, :mark_best]

  after_action :publish_answer, only: [:create]

  respond_to :js

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params))
  end

  def destroy
    @answer.destroy
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def mark_best
    @answer.mark_best
  end

  private

  def publish_answer
    return if @answer.errors.any?
    attachments = []
    @answer.attachments.each { |a| attachments << {id: a.id, identifier: a.file.identifier, url: a.file.url} }
    ActionCable.server.broadcast(
      "question_#{@question.id}_answers",
      answer: @answer,
      attachments: @attachments,
      author_question: @question.user.id
    )
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy]).merge(user_id: current_user.id)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]

  authorize_resource

  def index
    @answers = @question.answers
    respond_with(@answers, each_serializer: AnswersSerializer)
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with(@answer)
  end

  def create
    @answer = @question.answers.create(answer_params)
    respond_with(:api, :v1, @answer)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body).merge(user_id: current_resource_owner.id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div class="answer-#{answer.id}"
  - cache ['best_answer', question, answer]
    - if answer.best?
      b Best answer
      .best-answer
  - if can?(:mark_best, answer)
     = link_to 'Mark best', mark_best_answer_path(answer), method: :patch, remote: true

  = render 'questions/comments', entity: answer
  - cache answer do
    p
      = answer.body

- unless answer.id.nil?
  div class="answer-votes-#{answer.id}"
    = render 'questions/vote', entity: answer

  - if answer.persisted? && answer.attachments.present?
    = render 'attachments/attachments', entity: answer

  - if can?(:destroy, answer)
    p
      = link_to 'Delete answer', answer, method: :delete, remote: true
  - if can?(:update, answer)
    p
      = link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }

  br
    - if answer.persisted?
      = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
        = f.text_area :body, id: "body-answer-#{answer.id}"
        = f.submit 'Save'

app/views/answers/create.js.erb
$('.answers').html('<%= j render @answer %>');
$('#answer_body').val('');

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('.answer-<%= @answer.id %>').remove();
  $('.notice').html('Answer was successfully destroyed.');
<% else %>
  $('.alert').html('You can not remove an answer!');
<% end %>

app/views/answers/mark_best.js.erb
$('.answers').html('<%= j render @answer.question.answers.first_best %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>