config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]
  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  mount ActionCable.server => '/cable'

  match "/register_email" => "omnitokens#register_email", :via => :post
  match "/verify_email" => "omnitokens#verify_email", :via => :get

  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  respond_to :js

  def create
    @question = Question.find(params[:question_id])
    @subscription = @question.subscriptions.create(user: current_user)
    respond_with(@subscription)
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    @question = @subscription.question
    @subscription.destroy
    respond_with(@subscription)
  end
end

app/views/subscriptions/_subscription.html.slim
- if can?(:create, Subscription)
  - subscription = question.subscriptions.find_by(user: current_user)
  - if subscription
    = link_to 'Unsubscribe', subscription, method: :delete, remote: true
  - else
    = link_to 'Subscribe', question_subscriptions_path(question), method: :post, remote: true

app/views/subscriptions/create.js.erb
<% unless @subscription.errors.present? %>
  $('.subscription').html('<%= j render 'subscriptions/subscription', question: @question %>')
<% end %>

app/views/subscriptions/destroy.js.erb
<% if @subscription.destroyed? %>
  $('.subscription').html('<%= j render 'subscriptions/subscription', question: @question %>')
<% end %>