config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "questions#index"

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch :mark_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]
  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  mount ActionCable.server => '/cable'

  match "/register_email" => "omnitokens#register_email", :via => :post
  match "/verify_email" => "omnitokens#verify_email", :via => :get

  resource :search, only: [:show]

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/search.rb
class Search
  TYPES = %w(question answer comment user)

  def self.types
    TYPES
  end

  def self.results(query, scopes, page)
    classes = TYPES & scopes
    classes.map! { |scope| scope.capitalize.constantize }

    if classes.present?
      ThinkingSphinx.search(ThinkingSphinx::Query.escape(query), classes: classes, page: page, per_page: 5)
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  authorize_resource

  def show
    params[:scopes] = Search::TYPES if params[:scopes].blank?
    if params[:text]
      @results = Search.results(params[:text], params[:scopes], params[:page])
      respond_with(@results)
    end
  end
end

app/views/searches/_answers.html.slim
p
  | In question:
  = link_to result.question.title, question_path(result.question)
  br
  = result.body

app/views/searches/_comments.html.slim
p
  | In question:
  | &nbsp
  - if result.commentable_type == 'Question'
    = link_to result.commentable.title, question_path(result.commentable)
  - else
    = link_to result.commentable.question.title, question_path(result.commentable.question)
    br
    = "To answer: #{result.commentable.body}"
  br
  = result.body

app/views/searches/_questions.html.slim
p
  = link_to result.title, question_path(result)
  br
  = result.body

app/views/searches/_search.html.slim
h2 Results:
- if results.empty?
  p No matches
- else
  - results.each do |res|
    = render "searches/#{res.model_name.to_s.downcase}s", result: res
  = will_paginate results

app/views/searches/_users.html.slim
p
  = result.email

app/views/searches/show.html.slim
h1 Search:
= form_tag search_path, method: :get
  = label_tag :text
  = text_field_tag :text, params[:text]
  = label_tag :scopes, 'Scopes:'
  - Search.types.each_with_index do |type, index|
    = check_box_tag 'scopes[]', type
    = label_tag "scope_#{index}", type.capitalize
  = submit_tag 'Search'
.results
  = render 'searches/search', results: @results if @results